// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer environment variables for credentials in both browser (import.meta.env)
// and Node (process.env). Falling back to the existing hard-coded values only
// as a last-resort for local debugging.
// IMPORTANT: Do not commit production keys to source control. Rotate keys if
// these values are or were ever committed to a public repo.

const SUPABASE_URL =
  // Vite/browser build-time env
  (typeof import.meta !== 'undefined' && (import.meta as any).env?.VITE_SUPABASE_URL) ||
  // Node runtime env (for scripts/tests)
  process.env.VITE_SUPABASE_URL ||
  // fallback (existing value)
  'https://vwekhfalyqcawpvdbier.supabase.co';

const SUPABASE_PUBLISHABLE_KEY =
  (typeof import.meta !== 'undefined' && (import.meta as any).env?.VITE_SUPABASE_PUBLISHABLE_KEY) ||
  process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3ZWtoZmFseXFjYXdwdmRiaWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1MzcwOTgsImV4cCI6MjA3ODExMzA5OH0.P6w0a4U9xO4oiMTiMZxZH_59YX-LIw6uZ8-nHkbDSeY';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});